### ISSUE TITLE
Framework - `this.on` is not a function

### ISSUE THREAD

**Issue by mosure** [WebexSamples/webex-node-bot-framework#44]
Is there a workaround for this error?

```
"webex-node-bot-framework": "^2.3.4"
```

```
❯ node --version
v14.16.0
❯ node index.js
/home/mosure/ci-webex-bot/node_modules/webex-node-bot-framework/lib/framework.js:139
  this.on('error', err => {
       ^

TypeError: this.on is not a function
    at Module.Framework [as exports] (/home/mosure/ci-webex-bot/node_modules/webex-node-bot-framework/lib/framework.js:139:8)
    at Object.<anonymous> (/home/mosure/ci-webex-bot/node_modules/webex-node-bot-framework/index.js:3:20)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by jpjpjp** [comment]
@mosure I haven't encounters this before.   It looks like you are getting this just trying to start your program?

**Comment by jpjpjp** [comment]
@mosure will close this since I can't repro.  Feel free to re-open with more info!
